# Generated by Django 2.1.2 on 2018-11-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181103_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
